thymio-01:
  option_centers: [48, 163, 663]
  allowed_offsets: [10, 20, 10]

thymio-03:
  option_centers: [49, 148, 610]
  allowed_offsets: [15, 15, 10]

thymio-04:
  option_centers: [40, 153, 651]
  allowed_offsets: [15, 25, 10]

thymio-07:
  option_centers: [43, 149, 549]
  allowed_offsets: [15, 25, 10]

thymio-08:
  option_centers: [43, 145, 559]
  allowed_offsets: [15, 25, 10]

thymio-09:
  option_centers: [55, 194, 705]
  allowed_offsets: [20, 40, 10]

thymio-10:
  option_centers: [37, 145, 590]
  allowed_offsets: [15, 25, 10]

thymio-11:
  option_centers: [51, 179, 730]
  allowed_offsets: [15, 25, 10]

thymio-12:
  option_centers: [55, 177, 737]
  allowed_offsets: [15, 20, 10]

thymio-13:
  option_centers: [35, 139, 631]
  allowed_offsets: [15, 10, 10]

thymio-14:
  option_centers: [64, 226, 900]
  allowed_offsets: [15, 20, 10]

thymio-15:
  option_centers: [54, 194, 804]
  allowed_offsets: [20, 20, 10]

thymio-20:
  option_centers: [47, 156, 604]
  allowed_offsets: [15, 20, 10]

thymio-21:
  option_centers: [46, 148, 574]
  allowed_offsets: [15, 30, 10]